repos:

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix"]
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: git://github.com/dnephin/pre-commit-golang
    # Master as of 2021-04-01
    rev: ac0f6582d2484b3aa90b05d568e70f9f3c1374c7
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-lint
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: validate-toml
      - id: no-go-testing
      - id: gometalinter
      - id: golangci-lint
      - id: go-critic
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy
